name: Zip and Release SM-A556E_DFE

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      DEVICE: A556E
      VERSION: "1.5"
      ONEUI: "One UI 7"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP archive)
        run: |
          zip -r SM-${{ env.DEVICE }}_DFE_v${{ env.VERSION }}.zip . -x "README.md" "LICENSE" ".git/*" ".github/*"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "DFE v${{ env.VERSION }} for SM-${{ env.DEVICE }}"
          body: |
              Device: SM-${{ env.DEVICE }}
              Version: ${{ env.VERSION }}
              OS: ${{ env.ONEUI }}

              Based on recovery zip flash method

             ️ Be sure to format /data after flashing this! If there is an error on 'Unmounting /data..' try to reboot to recovery and retry again
          files: SM-${{ env.DEVICE }}_DFE_v${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
